project:
  output-dir: ./_site/fr

lang: fr

website:
  navbar:
    background: "#1F80EF"
    logo: "images/logo_sans_fond.png"
    left:
      - icon: bi-translate
        menu:
          - href: ../en
            text: English
          - href: ../fr
            text: Français
    right:
      - href: about_us.qmd
        text: À propos de nous
      - href: filmography.qmd
        text: Filmographie
      - href: contact.qmd
        text: Contact
        
  page-footer:
    left: 
      - icon: github
        href: https://github.com/ersatz-production/ersatz-production.github.io
        text: Dépôt GitHub
      - href: https://github.com/ersatz-production
        text: Organisation sur GitHub
    center:
      - href: https://ersatzproduction.com
        text: ersatzproduction.com
    right: 
      - href: privacy.html
        text: Politique de confidentialité
      - href: terms_and_conditions.html
        text: Conditions d'utilisation

 
execute:
  freeze: auto