project:
  type: website

website:
  title: "Ersatz Production"
  description: "Make your dreams come true"
  page-navigation: true
  reader-mode: true  
  navbar:
    title: "Ersatz Production"
    background: "#1F80EF"
    logo: "image/profile.jpeg"
    right:
      - href: about_us.qmd
        text: About Us
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
        
  page-footer:
    left: 
      - href: about.qmd
        text: About This Website
      - icon: github
        href: https://github.com/ersatz-production/ersatz-production.github.io
        text: GitHub Repository
      - href: https://github.com/ersatz-production
        text: GitHub Organisation
    center:
      - href: https://ersatzproduction.com
        text: ersatzproduction.com
    right: 
      - href: privacy.html
        text: Privacy Policy
      - href: terms_and_conditions.html
        text: Terms and Conditions
  site-url: https://ersatzproduction.com
  repo-url: https://github.com/ersatz-production/ersatz-production.github.io
  open-graph: true
  search: true
  
format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true
    include-after-body: plausible.html
    include-in-header:
    - text: |
        <link rel="icon" type="image/png" href="/image/favicon/favicon-48x48.png" sizes="48x48" />
        <link rel="icon" type="image/svg+xml" href="/image/favicon/favicon.svg" />
        <link rel="shortcut icon" href="/image/favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/image/favicon/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="Ersatz Production" />
        <link rel="manifest" href="/image/favicon/site.webmanifest" />
editor: source
execute:
  freeze: auto


