project:
  type: website

website:
  title: "Ersatz Production"
  favicon: "images/our_logo.jpeg"
  description: "Make your dreams come true"
  page-navigation: true
  reader-mode: true  
  navbar:
    title: "Ersatz Production"
    background: "#1F80EF"
    logo: "images/our_logo.jpeg"
    right:
      - href: about_us.qmd
        text: About Us
      - href: history.qmd
        text: History
      - href: contact.qmd
        text: Contact
        
  page-footer:
    left: 
      - href: about.qmd
        text: About This Website
      - icon: github
        href: https://github.com/ersatz-production/ersatz-production.github.io
        text: GitHub Repository
      - href: https://github.com/ersatz-production
        text: GitHub Organisation
    center:
      - href: https://ersatzproduction.com
        text: ersatzproduction.com
    right: 
      - href: privacy.html
        text: Privacy Policy
      - href: terms_and_conditions.html
        text: Terms and Conditions
  site-url: https://ersatzproduction.com
  repo-url: https://github.com/ersatz-production/ersatz-production.github.io
  open-graph: true
  search: true
  
format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    toc-expand: true
    include-after-body: plausible.html
    include-before-body: _include.html
    grid:
      sidebar-width: 100px
      body-width: 1300px
      margin-width: 100px
      gutter-width: 1.5rem
editor: source
execute:
  freeze: true


