project:
  output-dir: ./_site/en

lang: en

website:
  navbar:
    background: "#1F80EF"
    logo: "images/logo_sans_fond.png"
    left:
      - icon: bi-translate
        menu:
          - href: ../en
            text: English
          - href: ../fr
            text: Français
    right:
      - href: about_us.qmd
        text: About Us
      - href: filmography.qmd
        text: Filmography
      - href: contact.qmd
        text: Contact
        
  page-footer:
    left: 
      - icon: github
        href: https://github.com/ersatz-production/ersatz-production.github.io
        text: GitHub Repository
      - href: https://github.com/ersatz-production
        text: GitHub Organisation
      - icon: linkedin
        href: https://linkedin.com/company/ersatz-production
    center:
      - href: https://ersatzproduction.com
        text: ersatzproduction.com
    right: 
      - href: privacy.html
        text: Privacy Policy
      - href: terms_and_conditions.html
        text: Terms and Conditions

execute:
  freeze: auto