project:
  type: website

website:
  title: "Ersatz Production"
  description: "Make your dreams come true"
  page-navigation: false
  reader-mode: false  
  favicon: "image/favicon/apple-touch-icon.png"
  navbar:
    title: false
    background: "#1F80EF"
    logo: "image/favicon/apple-touch-icon.png"
    right:
      - href: about_us.qmd
        text: About Us
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
        
  page-footer:
    left: 
      - href: about.qmd
        text: About This Website
      - icon: github
        href: https://github.com/ersatz-production/ersatz-production.github.io
        text: GitHub Repository
      - href: https://github.com/ersatz-production
        text: GitHub Organisation
    center:
      - href: https://ersatzproduction.com
        text: ersatzproduction.com
    right: 
      - href: privacy.html
        text: Privacy Policy
      - href: terms_and_conditions.html
        text: Terms and Conditions
  site-url: https://ersatzproduction.com
  repo-url: https://github.com/ersatz-production/ersatz-production.github.io
  margin-header: |
    ![](image/profile.png)
  open-graph: true
  search: true
  
format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true
    include-after-body: plausible.html

editor: source
execute:
  freeze: auto


