project:
  type: website
    
profile:
  default: french
  group: [french, english]



website:
  site-url: https://ersatzproduction.com
  repo-url: https://github.com/ersatz-production/ersatz-production.github.io
  open-graph: true
  search: true

execute:
  freeze: true