---
css: styles.css
---

::: {.filmography}

## Vincent Lettry {.creator}

::: {.project}
### MORITURI PODCAST
::: {.project-details}
::: {.content-visible when-profile="english"}
- Podcast, 15 episodes, 2022-2023
- Written, Directed, Produced, Voice
- [Listen on Buzzsprout](https://morituripodcast.buzzsprout.com)
:::
::: {.content-visible when-profile="french"}
- Podcast, 15 épisodes, 2022-2023
- Scénario, Réalisation, Production, Voix
- [Écouter sur Buzzsprout](https://morituripodcast.buzzsprout.com)
:::
:::
:::

## Matthias Klee {.creator}

::: {.project}
### MORITURI PODCAST
::: {.project-details}
::: {.content-visible when-profile="english"}
- Podcast, 15 episodes, 2022-2023
- Written, Directed, Produced, Edited, Voice
- [Listen on Buzzsprout](https://morituripodcast.buzzsprout.com)
:::
::: {.content-visible when-profile="french"}
- Podcast, 15 épisodes, 2022-2023
- Scénario, Réalisation, Production, Montage, Voix
- [Écouter sur Buzzsprout](https://morituripodcast.buzzsprout.com)
:::
:::
:::
## Rani Gillioz {.creator}

::: {.project}
### DEMONS
::: {.project-details}
::: {.content-visible when-profile="english"}
- Official music video for *Demons* by Desmond, 5 min. 47 sec., 2016
- Directed, Produced, Shot, Edited
:::
::: {.content-visible when-profile="french"}
- Clip vidéo officiel pour *Demons* par Desmond, 5 min. 47 sec., 2016
- Réalisation, Production, Image, Montage
:::
:::
:::

::: {.project}
::: {.content-visible when-profile="english"}
### THE UNNAMEABLE
:::
::: {.content-visible when-profile="french"}
### L'INNOMMABLE
:::
::: {.project-details}
::: {.content-visible when-profile="english"}
- Self-produced and self-financed feature film, 99 min., 2014
- Directed, Produced, Written, Shot, Edited, Music
- [Internet Link to the Trailer](https://vimeo.com/ranigillioz/linnommable-trailer)
:::
::: {.content-visible when-profile="french"}
- Long-métrage de fiction autoproduit et autofinancé, 99 min., 2014
- Réalisation, Production, Scénario, Image, Montage, Musique
- [Lien internet vers le trailer](https://vimeo.com/ranigillioz/linnommable-trailer)
:::
:::
:::

::: {.project}
::: {.content-visible when-profile="english"}
### THE ANT THAT SWALLOWED THE SUN
:::
::: {.content-visible when-profile="french"}
### LA FOURMI QUI AVALA LE SOLEIL
:::
::: {.project-details}
::: {.content-visible when-profile="english"}
- Graduation feature film, 98 min., 2010
- Directed, Produced, Written, Shot, Edited, Music
:::
::: {.content-visible when-profile="french"}
- Long-métrage de fiction – travail de fin d’études, 98 min., 2010
- Réalisation, Production, Scénario, Image, Montage, Musique
:::
:::
:::

::: {.project}
### Mr. COWARD
::: {.project-details}
::: {.content-visible when-profile="english"}
- Mini fiction short film, 2 min. 20 sec., 2010
- Directed, Written, Shot, Edited, Music
:::
::: {.content-visible when-profile="french"}
- Mini court-métrage de fiction, 2 min. 20 sec., 2010
- Réalisation, Scénario, Image, Montage, Musique
:::
:::
:::
::: {.project}
### NEONS
::: {.project-details}
::: {.content-visible when-profile="english"}
- Official music video for I believe in love at first sight by Neons, 3 min. 38 sec., 2010
- Directed, Shot, Edited
:::
::: {.content-visible when-profile="french"}
- Clip vidéo officiel pour *I believe in love at first sight par Neons*, 3 min. 38 sec., 2010
- Réalisation, Image, Montage
:::
:::
:::

::: {.project}
### [drink me]
::: {.project-details}
::: {.content-visible when-profile="english"}
- Documentary short film, 21 min., 2008
- Directed, Shot, Edited, Music
:::
::: {.content-visible when-profile="french"}
- Court-métrage documentaire, 21 min., 2008
- Réalisation, Image, Montage, Musique
:::
:::
:::

::: {.project}
### CELLOPHANE, THREADS AND MILK
::: {.project-details}
::: {.content-visible when-profile="english"}
- Unofficial music video for *Solitaire* by Notwist, 4 min., 2008
- Directed, Shot, Edited
:::
::: {.content-visible when-profile="french"}
- Clip vidéo officiel pour *Solitaire* par Notwist, 4 min., 2008
- Réalisation, Image, Montage
:::
:::
:::

::: {.project}
### THIS IS MILK. THIS IS TREE.
::: {.project-details}
::: {.content-visible when-profile="english"}
- Fiction short film, 8 min., 2008
- Directed, Written, Shot, Edited, Music
:::
::: {.content-visible when-profile="french"}
- Court-métrage de fiction, 8 min., 2008
- Réalisation, Scénario, Image, Montage, Musique
:::
:::
:::

::: {.project}
### BODY
::: {.project-details}
::: {.content-visible when-profile="english"}
- Fiction short film, 20 min., 2008
- Directed, Produced, Written, Shot, Edited
:::
::: {.content-visible when-profile="french"}
- Court-métrage de fiction, 20 min., 2008
- Réalisation, Production, Scénario, Image, Montage
:::
:::
:::

::: {.project}
::: {.content-visible when-profile="english"}
### SOMETIMES, MY CAT LIKES ME...
:::
::: {.content-visible when-profile="french"}
### PARFOIS, MON CHAT M'AIME BIEN...
:::
::: {.project-details}
::: {.content-visible when-profile="english"}
- Experimental short film, 30 min., 2007
- Directed, Produced, Written, Shot, Edited, Music
:::
::: {.content-visible when-profile="french"}
- Court-métrage expérimental, 30 min., 2007
- Réalisation, Production, Scénario, Image, Montage, Musique
:::
:::
:::

:::
